[package]
name = "zeitline"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["teismar"]
license = "MIT"
description = "A Typst package for plotting timelines"
repository = "https://github.com/teismar/zeitline"
keywords = ["timeline", "visualization"]
categories = ["visualization", "components"]
